name: 插件构建

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'

jobs:
  build-plugins:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.401

    - name: 更新源码
      working-directory: ./
      run: |
        chmod a+x ./build/update.sh
        ./build/update.sh

    - name: 构建 源码
      working-directory: ./
      run: |
        chmod a+x ./build/build-plugin.sh
        ./build/build-plugin.sh

    - name: 上传 colordesktop-plugin-AnalogClockPlugin
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin-AnalogClockPlugin"
        path: src/build_out/Debug/net8.0/plugins/AnalogClockPlugin
    
    - name: 上传 colordesktop-plugin-CalendarPlugin
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin-CalendarPlugin"
        path: src/build_out/Debug/net8.0/plugins/CalendarPlugin

    - name: 上传 colordesktop-plugin-ClockPlugin
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin-ClockPlugin"
        path: src/build_out/Debug/net8.0/plugins/ClockPlugin

    - name: 上传 colordesktop-plugin-CoreLib
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin-CoreLib"
        path: src/build_out/Debug/net8.0/plugins/CoreLib

    - name: 上传 colordesktop-plugin-WeatherPlugin
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin-WeatherPlugin"
        path: src/build_out/Debug/net8.0/plugins/WeatherPlugin

    - name: 上传 colordesktop-plugin
      uses: actions/upload-artifact@v4
      with:
        name: "colordesktop-plugin"
        path: src/build_out/Debug/net8.0/plugins/**